### ISSUE TITLE
Mention relevant limitations of use

### ISSUE THREAD

**Issue by pka** [riccardoklinger/HEREqgis#9]
Exerpt from Acceptable Use Policy (“AUP”):

Use of any HERE products, services, data, databases, APIs, platforms, infrastructure, applications, websites or other offerings (each, a “HERE Property”) is subject to this Acceptable Use Policy (“AUP”).

**Application Restrictions**

Unless otherwise permitted in your commercial agreement with HERE, **HERE Properties may not be used in connection with** any of the following:
[...]
    - **GIS (geographic information systems) applications,** such as applications that analyze, process or visualize (or any combination of them) information **in order to manage land use, natural resources, environment, urban or enterprise facilities, communications or utility networks or any other fixed assets**

**Comment by riccardoklinger** [comment]
Can you please share a link to this ressource so I can check it with my contact at HERE?

**Comment by riccardoklinger** [comment]
ah, here: https://legal.here.com/en-gb/terms/acceptable-use-policy

**Comment by riccardoklinger** [comment]
from my contact at here: "Die Service Terms auf die du verweist sind nicht relevant für euch. Bei Registrierung auf unserem Developer Portal akzeptiert man die folgenden T&Cs: https://developer.here.com/terms-and-conditions (den Link findest du unter den Pricing Plans rechts unten)."

**Comment by pka** [comment]
Really? The developer T&Cs refer to the AUP as well:

> You are not allowed to use any data, content, materials or services of HERE in a way that is not specified in these Terms or that is not compliant with the HERE Acceptable Use Policy.

**Comment by riccardoklinger** [comment]
one more input on this @pka : When agreeing on the Freemium plan you will see the [Terms and Conditions](https://developer.here.com/terms-and-conditions#terms_sec5). It is clearly stated there: 

*Section “Application Restrictions” as set out in the Acceptable Use Policy shall not apply*
